name = "server"
type = "webpack"
account_id = "fa5d12d53756c48e3c77b7600d4e2ded"
workers_dev = true
route = ""
zone_id = "b1d2cdf4b5d46f730a0e82e341225e01"
kv_namespaces = [
         { binding = "BUCKET", id = "7cc5339de5db48cfbdf8eb39e83f00bb" }
]
